### PR TITLE
Add device type(s) in node-view - Endpoint list

### PR DESCRIPTION
**Pull request by lboue**
Add device type(s) in node-view. It should fix this request: 
- #941

image

### CODE REVIEW

**Comment by lboue** [comment]
Is there a manual compilation to do after a modification in a dashboard with the tsc command?

**Comment by lboue** [comment]
It now works. Could you do a review?

**Comment by lboue** [comment]
Is everything OK?

**Review by marcelveldt — APPROVED** [review]
Thanks!

**Pull request merged**
