### PR TITLE
Bump to CHIP version a1643eee5e (2022-08-10 00:03:09 -0700)

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Comment by agners** [comment]
This currently fails to serialize a complete device read with:

```
TypeError: WrongTypeError.__init__() missing 2 required positional arguments: 'field_type' and 'value'
```

**Comment by agners** [comment]
There are 4 Cluster Objects which fail deserialization (TLV deserialization which is part of the CHIP Python code):

```
2022-08-10 21:32:25 allenwind root[2394191] ERROR Error converting TLV to Cluster Object for path: Endpoint = 0, cluster = <class 'chip.clusters.Objects.ThreadNetworkDiagnostics'>
2022-08-10 21:32:25 allenwind root[2394191] ERROR |-- Exception: ValueError("Failed to decode field [].channel, expected type <class 'chip.tlv.uint'>, got <class 'chip.clusters.Attribute.ValueDecodeFailure'>")
2022-08-10 21:32:25 allenwind root[2394191] ERROR Error converting TLV to Cluster Object for path: Endpoint = 0, cluster = <class 'chip.clusters.Objects.WiFiNetworkDiagnostics'>
2022-08-10 21:32:25 allenwind root[2394191] ERROR |-- Exception: WrongTypeError()
2022-08-10 21:32:25 allenwind root[2394191] ERROR Error converting TLV to Cluster Object for path: Endpoint = 0, cluster = <class 'chip.clusters.Objects.AdministratorCommissioning'>
2022-08-10 21:32:25 allenwind root[2394191] ERROR |-- Exception: WrongTypeError()
2022-08-10 21:32:25 allenwind root[2394191] ERROR Error converting TLV to Cluster Object for path: Endpoint = 1, cluster = <class 'chip.clusters.Objects.TestCluster'>
2022-08-10 21:32:25 allenwind root[2394191] ERROR |-- Exception: ValueError("Failed to decode field [].generalErrorBoolean, expected type <class 'bool'>, got <class 'chip.clusters.Attribute.ValueDecodeFailure'>")
```

Some of them have been there before, but what is new is that some cause a `WrongTypeError` exception. it seems that our JSON serializer chocks on those.

**Comment by agners** [comment]
With the last commit the serialization issue is addressed. Controlling a light seems to work again.

**Comment by balloob** [comment]
In 0d99365b780e99cf811aefbe1d30cb8ec6dafdfb you manually removed some things from `device_types.py`. Instead you should update the generate script to address these issues.

**Comment by agners** [comment]
Seems when they got removed from various places `matter-devices.xml` got missed. Created a PR https://github.com/project-chip/connectedhomeip/pull/21818. Regenerated the devices using that updated xml.

**Comment by balloob** [comment]
We are the only people using that XML I think 😬

**Review by balloob — APPROVED** [review]

**Pull request merged**
