### PR TITLE
Use mkdirs for paa_root_certs as the intermediate directories do not exist

### PR DESCRIPTION
**Pull request by D3v01dZA**
Fixes https://github.com/home-assistant-libs/python-matter-server/issues/704

### CODE REVIEW

**Comment by D3v01dZA** [comment]
paa_dir is a pathlib.Path

https://github.com/home-assistant-libs/python-matter-server/blob/main/matter_server/server/const.py#L16
https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

**Review by marcelveldt — APPROVED** [review]
Looks fine to me, thanks!

**Comment by petrij98** [comment]
Are we able to get this fixed up soon? I'm trying to create a new Python Matter container and this very issue is keeping me from running it.

**Comment by petrij98** [comment]
How are we looking with pushing these changes? I've been trying to get a new Python Matter container running today and have been plagued by this very issue.

**Comment by olavt** [comment]
When will a new build be triggered including this fix?

**Comment by MadSpindel** [comment]
@marcelveldt Can you trigger a new release version with this fix?

**Comment by marcelveldt** [comment]
First of all, not very nice to start tagging people to get them to do a release, especially not on a public holiday.
Second of all, we provide the docker image on a best-effort base, its not officially supported. If you are smart enough that you think you should be running your own docker container to run the Matter server (ignoring all our warnings that running Matter in docker is not as straight forward as you might think) you will be smart enough to just use specific docker tag of the Matter server. Never a good practice to just run "latest" - run a specific version and upgrade with care, especially for docker images that are provided on a best effort base.

**Pull request merged**
