### PR TITLE
Add helper method get_attribute to MatterDeviceTypeInstance

### PR DESCRIPTION
**Pull request by ArturoGuerra**
This method makes it easier to get a `MatterAttribute` from a `MatterDeviceTypeInstance`

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
What's the current alternative to the new helper?

**Comment by ArturoGuerra** [comment]
It would be something like this `instance.node.get_attribute(instance.endpoint, Clusters.LevelControl, "minLevel")` and with this it would just be `instance.get_attribute(Clusters.LevelControl, "minLevel")`

**Comment by ArturoGuerra** [comment]
It's related to the last part of the comment here https://github.com/home-assistant-libs/python-matter-server/pull/189#discussion_r1096370465

**Comment by balloob** [comment]
I suggest that we don't merge this right now. Marcel is planning on re-doing how data is stored both on the server and the client side as tracked here: https://github.com/orgs/home-assistant-libs/projects/1?pane=issue&itemId=16855348

**Comment by ArturoGuerra** [comment]
in that case, we should also hold off on this pull request https://github.com/home-assistant-libs/python-matter-server/pull/189

**Comment by marcelveldt** [comment]
I was thinking of fixing the bridge support and then look at the datamodel but I guess we need to do the datamodel first and then fix the bridges

**Comment by marcelveldt** [comment]
This one can be closed now that its all handled at endpoint level

**Pull request closed without merging**
