### PR TITLE
Fix Nullable values in write attributes procedure

### PR DESCRIPTION
**Pull request by BDeliers**
Writing attributes values with JSON data is allowed in Matter, for instance with the ACL cluster we can send this payload:
<details>
<summary>Expand</summary>

```
[
    {
        "fabricIndex":0,
        "privilege":5,
        "authMode":2,
        "subjects":[
            112233
        ],
        "targets":null
    },
    {
        "fabricIndex":0,
        "privilege":1,
        "authMode":2,
        "subjects":[
            4444,
            5555,
            6666
        ],
        "targets":null
    },
    {
        "fabricIndex":0,
        "privilege":3,
        "authMode":3,
        "subjects":[
            123,
            456
        ],
        "targets":[
            {
                "cluster":6,
                "endpoint":null,
                "deviceType":null
            },
            {
                "cluster":null,
                "endpoint":1,
                "deviceType":null
            },
            {
                "cluster":8,
                "endpoint":2,
                "deviceType":null
            }
        ]
    }
]
```

</details>

When Python parses this JSON, the `null` value is then converted to a Python `None`. This `None` is not allowed by the Matter SDK, at the opposite of the `Nullable` type which is defined in the SDK to handle this kind of situation.

This pull-request is there to fix this issue: the Python `None` is converted to a Matter `Null` value of type `Nullable`.

### CODE REVIEW

**Comment by marcelveldt** [comment]
First of all thanks for the PR!
I'm sorry but this is the wrong way to fix this - it needs to be addressed in our helper that reconstructs the Cluster object from the json in the api. 

It should be as easy as replacing the value assignment with our "parse_value" helper form utils.
That is already ready for the custom sdk types.

If you want I can make the adjustment and would be great if you can test if that gives the desired behavior

**Comment by BDeliers** [comment]
Thanks for your feedback. If I understand properly what you said, it can be fixed by changing [Line 137 of matter_server/common/helpers/util.py](https://github.com/home-assistant-libs/python-matter-server/blob/main/matter_server/common/helpers/util.py#L137) from 
```
if value is None and value_type is Nullable:
        return None
```
to
```
if value is None and value_type is Nullable:
        return Null
```

?

**Comment by marcelveldt** [comment]
Well, yes but we need some more. We will also need a boolean option to that util function if the custom types are allowed.
Because in this case you are going from [json --> dataclass convertor --> SDK] and then the custom SDK types are needed but when we do the same in e.g. Home Assistant or any other consumer of the lib we need to convert the values.

Want me to edit the PR to adjust the utils func so you can use it in the write command ?

**Comment by BDeliers** [comment]
It seems that you know the project way better than I do.
Yes please, do the changes and I will then test with my use case !

**Comment by marcelveldt** [comment]
I will do so monday. I'll let you know once its ready to test

**Comment by marcelveldt** [comment]
I have modified your PR with the adjustments. Now all values that are sent to the SDK will be in the SDK's custom data types such as Nullable, uint and float32

**Comment by marcelveldt** [comment]
I've tested both sending commands and write attribute and both still work.

**Review by agners — APPROVED** [review]

**Pull request merged**
