### PR TITLE
Enable dashboard in dev build

### PR DESCRIPTION
**Pull request by Chapoly1305**
Fix for https://github.com/home-assistant-libs/python-matter-server/issues/776

### CODE REVIEW

**Review by marcelveldt — APPROVED** [review]
LGTM, thanks!

**Comment by marcelveldt** [comment]
@Chapoly1305 can you have a look at the issues found by the linter ?

**Comment by Chapoly1305** [comment]
@marcelveldt thanks for the notice. I adjusted the nodejs installer and use the official version, the previous in code was from a third-party website. Lint issue should also be fixed.

**Comment by marcelveldt** [comment]
Still a lint issue found ?

**Comment by Chapoly1305** [comment]
Now it shall be all fixed. Please help to trigger the scan again, thanks! :) @marcelveldt

**Review by marcelveldt — APPROVED** [review]
Thanks, @Chapoly1305 !

**Pull request merged**
